FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ../backend/req.txt .

RUN apt-get update && \
    pip install -r req.txt && \
    apt-get -y install \
    default-libmysqlclient-dev \
    python3-dev \
    netcat

WORKDIR /app

ADD ../backend /app/

