image: docker-compose:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy


build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose -f docker-composes/prod_docker-compose.yml build
    - docker-compose -f docker-composes/prod_docker-compose.yml push


test:
  stage: test
  script:
    - docker-compose -f docker-compose/prod_docker-compose.yml pull

