image: docker-compose:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy



build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - docker-compose -f prod_docker_compose.yml build
    - docker-compose -f prod_docker_compose.yml push


