image: docker-compose:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy


test:
  stage: test
#  before_script:
#    - sudo usermod -aG docker gitlab-runner
#    - sudo systemctl status docker
#    - sudo service docker restart
  script:
    - docker run hello-world
