image: docker-compose:latest

stages:
  - build
  - test
  - deploy


test:
  stage: test
  before_script:
    - usermod -aG docker gitlab-runner
    - systemctl status docker
    - sudo service docker restart
  script:
    - docker run hello-world
