image: docker:20-dind
services:
  - name: docker:20-dind
    command: ["--tls=false"]

stages:
  - build

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_TLS_CERTDIR: ""
#  DOCKER_DRIVER: overlay2

before_script:
  - whoami
  - apk add docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com


build:
  stage: build
  script:
     - docker-compose -f docker-composes/dev_ci_docker-compose.yml images
  tags:
  - docker



# -------------------------------------------------------

# ERROR: Couldn't connect to Docker daemon at http://docker:2375 - is it running?

#image: docker:stable
#services:
#  - docker:dind
#
#stages:
#  - build
#
#
#before_script:
#  - apk add docker-compose
#  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#
#build:
#  stage: build
#  script:
#     - docker-compose -f docker-composes/dev_ci_docker-compose.yml images
#  tags:
#  - docker

#--------------------------------------------------------

# Error Job failed: failed to pull image "docker/compose:stable

#image: docker/compose:stable
#
#services:
#  - docker:stable
#
#stages:
#  - build
#build:
#  stage: build
#  script:
#    - docker-compose -f dev_ci_docker-compose.yml images
#  tags:
#    - docker



#------------------------------------------------------------

# ERROR: docker-compose: not found

#image: docker:stable
#
#services:
#  - docker:stable
#
#stages:
#  - build
#
#build:
#  stage: build
#  script:
#    - docker-compose -f dev_ci_docker-compose.yml images
#  tags:
#    - docker

#-------------------------------------------------------------


