image: docker-compose:latest
services:
  - docker:dind
stages:
  - dev
  - prod

variables:
  D_C_DEV: docker-compose -f docker-composes/dev_ci_docker-compose.yml

dev_build:
  stage: dev
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - $D_C_DEV build
    - $D_C_DEV push

dev_test:
  stage: dev
  before_script:
    - $D_C_DEV pull
    - $D_C_DEV up -d
  script:
    - $D_C_DEV run --rm web python manage.py test

dev_destroy:
  stage: dev
  script:
    - $D_C_DEV down -v