#variables:
#  DOCKER_HOST: tcp://docker:2375/
#  DOCKER_DRIVER: overlay2

image: docker-compose:latest
services:
  - docker:dind
stages:
  - build
  - test
  - deploy



build:
  stage: build
  script:
#    - apk add --no-cache docker-compose
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
    - echo CI_REGISTRY_USER CI_REGISTRY_USER
    - echo CI_JOB_TOKEN CI_JOB_TOKEN
    - echo CI_REGISTRY CI_REGISTRY

    - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - systemctl start docker
    - docker-compose -f docker-composes/prod_docker-compose.yml build
    - docker-compose -f docker-composes/prod_docker-compose.yml push



