FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && \
    apt-get -y install \
    default-libmysqlclient-dev \
    python3-dev \
    netcat

RUN pip install --upgrade pip

COPY dev_req.txt .

ADD . /app/

RUN pip install -r dev_req.txt


